name: Test code
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        uses: actions/checkout@v3
      - name: NodeJS install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: npm ci
      - name: Run tests
        run: npm test