name: GitHub Release
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install release action dependencies
        run: npm install conventional-changelog-conventionalcommits

      - name: Create Tag with Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.1.0
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file-path: '.github/workflows/changelog.conf'
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
          skip-tag: "true"
          tag-prefix: ""

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ steps.changelog.outputs.tag }}'
          sha: '${{ github.event.pull_request.head.sha }}'
